server:
  port: 8180
  servlet:
    contex-path: /shop
spring:
  datasourse:
    driver-class-name:org.h2.Driver
  url: jdbc:h2:mem:mydatabase;MODE=PostgeSQL
  username: sa
  password:
jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect